# Professional PDF report generation (Phase D.2).
#
# Renders a structured ECGReport (HR, rhythm, intervals, AI diagnoses) plus the
# original photo and the digitized 12-lead tracing into a single A4 PDF using
# reportlab. This layer NEVER computes clinical findings; it only typesets what
# the deterministic + model pipeline already produced. A disclaimer on every
# page makes the research/decision-support framing explicit.

from __future__ import annotations

import io
from datetime import datetime
from pathlib import Path

from PIL import Image
from reportlab.lib import colors  # type: ignore[import-untyped]
from reportlab.lib.enums import TA_CENTER, TA_LEFT  # type: ignore[import-untyped]
from reportlab.lib.pagesizes import A4  # type: ignore[import-untyped]
from reportlab.lib.styles import (  # type: ignore[import-untyped]
    ParagraphStyle,
    getSampleStyleSheet,
)
from reportlab.lib.units import mm  # type: ignore[import-untyped]
from reportlab.pdfbase import pdfmetrics  # type: ignore[import-untyped]
from reportlab.pdfbase.ttfonts import TTFont  # type: ignore[import-untyped]
from reportlab.platypus import (  # type: ignore[import-untyped]
    Image as RLImage,
)
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from src.measurement.intervals import IntervalMeasurements
from src.report.structured_report import ECGReport
from src.report.vtsvt_pdf import vtsvt_pdf_section

# Verdict palette mirrors the web headline card so print and screen agree.
_VERDICT_COLORS: dict[str, tuple[str, str]] = {
    "Normal ECG": ("#166534", "#F0FDF4"),
    "Abnormal ECG": ("#991B1B", "#FEF2F2"),
    "Indeterminate ECG": ("#92400E", "#FFFBEB"),
}
_DEFAULT_VERDICT_COLOR: tuple[str, str] = ("#1E3A8A", "#F8FAFC")

# reportlab's built-in Helvetica lacks Turkish glyphs (ş, ı, ğ, İ render as
# boxes), which breaks the Turkish AI summary. DejaVu Sans (shipped with
# matplotlib, already a dependency) has full Turkish coverage. Register it once
# and use it everywhere; fall back to Helvetica if registration fails (English
# still renders fine).
_FONT_REGULAR = "Helvetica"
_FONT_BOLD = "Helvetica-Bold"


def _register_unicode_fonts() -> None:
    global _FONT_REGULAR, _FONT_BOLD
    if _FONT_REGULAR == "CorioSans":  # already registered
        return
    try:
        import matplotlib

        ttf_dir = Path(matplotlib.__file__).parent / "mpl-data" / "fonts" / "ttf"
        pdfmetrics.registerFont(TTFont("CorioSans", str(ttf_dir / "DejaVuSans.ttf")))
        pdfmetrics.registerFont(
            TTFont("CorioSans-Bold", str(ttf_dir / "DejaVuSans-Bold.ttf"))
        )
        # Map the family so inline <b> tags in Paragraphs use the bold TTF
        # (otherwise <b> falls back to Helvetica-Bold and Turkish breaks again).
        pdfmetrics.registerFontFamily(
            "CorioSans", normal="CorioSans", bold="CorioSans-Bold"
        )
        _FONT_REGULAR = "CorioSans"
        _FONT_BOLD = "CorioSans-Bold"
    except Exception:  # noqa: BLE001 — fall back to Helvetica (Latin-only)
        pass


_DISCLAIMER: str = (
    "<b>Disclaimer:</b> This report is generated by an experimental AI pipeline "
    "for research and educational purposes only. It is NOT a medical device and "
    "must NOT be used for clinical decision-making. Final responsibility for any "
    "interpretation rests with a qualified reviewing clinician."
)


def _styles() -> dict[str, ParagraphStyle]:
    """Build the paragraph styles used across the report."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "CorioTitle",
            parent=base["Title"],
            fontName=_FONT_BOLD,
            fontSize=20,
            textColor=colors.HexColor("#1E3A8A"),
            spaceAfter=2,
            alignment=TA_LEFT,
        ),
        "subtitle": ParagraphStyle(
            "CorioSubtitle",
            parent=base["Normal"],
            fontName=_FONT_REGULAR,
            fontSize=9,
            textColor=colors.HexColor("#64748B"),
        ),
        "section": ParagraphStyle(
            "CorioSection",
            parent=base["Heading2"],
            fontName=_FONT_BOLD,
            fontSize=12,
            textColor=colors.HexColor("#1E3A8A"),
            spaceBefore=10,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "CorioBody",
            parent=base["Normal"],
            fontName=_FONT_REGULAR,
            fontSize=10,
            textColor=colors.HexColor("#0F172A"),
            leading=14,
        ),
        "verdict": ParagraphStyle(
            "CorioVerdict",
            parent=base["Normal"],
            fontName=_FONT_REGULAR,
            fontSize=16,
            leading=20,
        ),
        "disclaimer": ParagraphStyle(
            "CorioDisclaimer",
            parent=base["Normal"],
            fontName=_FONT_REGULAR,
            fontSize=8,
            textColor=colors.HexColor("#475569"),
            leading=11,
            alignment=TA_CENTER,
        ),
        "caption": ParagraphStyle(
            "CorioCaption",
            parent=base["Normal"],
            fontName=_FONT_REGULAR,
            fontSize=8,
            textColor=colors.HexColor("#64748B"),
            alignment=TA_CENTER,
        ),
    }


def build_pdf_report(
    report: ECGReport,
    *,
    output_path: Path,
    original_image: Image.Image | None = None,
    signal_image: Image.Image | None = None,
    intervals: IntervalMeasurements | None = None,
    narrative: str | None = None,
    generated_at: datetime | None = None,
) -> Path:
    """Render a structured report to a professional A4 PDF.

    Args:
        report: assembled ECGReport (verdict, HR, rhythm, intervals, diagnoses).
        output_path: where to write the PDF.
        original_image: the uploaded ECG photo (thumbnail in the report).
        signal_image: the digitized 12-lead tracing (full-width figure).
        intervals: raw interval measurements, for the per-beat/quality footer.
        narrative: optional LLM natural-language summary of the findings.
        generated_at: timestamp; defaults to now() at call time.

    Returns:
        The path the PDF was written to.
    """
    _register_unicode_fonts()
    styles = _styles()
    stamp = generated_at or datetime.now()

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title="CorioECG — AI-Assisted ECG Analysis Report",
    )

    story: list = []
    story.append(Paragraph("CorioECG — AI-Assisted ECG Analysis Report", styles["title"]))
    story.append(
        Paragraph(
            f"Generated: {stamp.strftime('%Y-%m-%d %H:%M')} &nbsp;·&nbsp; "
            "Research / educational use only",
            styles["subtitle"],
        )
    )
    story.append(Spacer(1, 8))

    story.append(_verdict_block(report, styles))
    story.append(Spacer(1, 6))

    story.append(Paragraph("Rhythm &amp; Rate", styles["section"]))
    story.append(_rhythm_table(report))

    story.append(Paragraph("Interval Measurements", styles["section"]))
    story.append(_intervals_table(report, intervals))

    story.extend(vtsvt_pdf_section(report, styles))

    story.append(Paragraph("AI Diagnoses (ECGFounder top-5)", styles["section"]))
    story.append(_diagnoses_table(report))

    if narrative:
        story.append(Paragraph("AI Summary", styles["section"]))
        for para in _narrative_paragraphs(narrative):
            story.append(Paragraph(para, styles["body"]))
            story.append(Spacer(1, 4))

    images_flowable = _images_row(original_image, signal_image, styles)
    if images_flowable is not None:
        story.append(Paragraph("ECG Images", styles["section"]))
        story.append(images_flowable)

    story.append(Spacer(1, 12))
    story.append(Paragraph(_DISCLAIMER, styles["disclaimer"]))

    doc.build(story)
    return output_path


def _verdict_block(report: ECGReport, styles: dict[str, ParagraphStyle]) -> Table:
    """The colored headline: overall assessment + reasons."""
    fg_hex, bg_hex = _VERDICT_COLORS.get(report.overall_assessment, _DEFAULT_VERDICT_COLOR)
    fg = colors.HexColor(fg_hex)

    hr_text = (
        f"{report.heart_rate_bpm:.0f} bpm" if report.heart_rate_bpm is not None else "n/a"
    )
    lines = [
        f"<b><font color='{fg_hex}' size='16'>{report.overall_assessment}</font></b>",
        f"<font size='10'>Rhythm: <b>{report.rhythm_classification}</b> &nbsp;·&nbsp; "
        f"HR: <b>{hr_text}</b></font>",
    ]
    if report.ectopy_present:
        lines.append(
            f"<font size='10' color='#B91C1C'>{report.pvc_count} PVC-like beat(s) detected</font>"
        )
    if report.abnormal_reasons:
        bullets = "".join(f"• {r}<br/>" for r in report.abnormal_reasons)
        lines.append(f"<font size='9' color='{fg_hex}'>{bullets}</font>")

    cell = Paragraph("<br/>".join(lines), styles["body"])
    table = Table([[cell]], colWidths=[doc_width()])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(bg_hex)),
                ("LINEBEFORE", (0, 0), (0, -1), 3, fg),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    return table


def _rhythm_table(report: ECGReport) -> Table:
    hr_text = (
        f"{report.heart_rate_bpm:.0f} bpm" if report.heart_rate_bpm is not None else "n/a"
    )
    data = [
        ["Heart rate", hr_text, "Rhythm", report.rhythm_classification],
        [
            "Rate category",
            report.rate_category,
            "Ectopy",
            f"{report.pvc_count} PVC-like" if report.ectopy_present else "none",
        ],
    ]
    table = Table(data, colWidths=[doc_width() * f for f in (0.18, 0.32, 0.18, 0.32)])
    table.setStyle(_kv_table_style())
    return table


def _intervals_table(
    report: ECGReport,
    intervals: IntervalMeasurements | None,
) -> Table:
    def fmt(value: float | None) -> str:
        return f"{value:.0f} ms" if value is not None else "n/a"

    flags = report.interval_flags
    header = ["PR", "QRS", "QT", f"QTc ({report.qtc_formula})"]
    values = [fmt(report.pr_ms), fmt(report.qrs_ms), fmt(report.qt_ms), fmt(report.qtc_ms)]
    # Keep cells short: the table shows a one-word status; the full explanation
    # (e.g. "prolonged — consider first-degree AV block") lives in the verdict
    # block above, where it has room to breathe.
    flag_row = [
        _short_flag(flags.get("pr")),
        _short_flag(flags.get("qrs")),
        "—",
        _short_flag(flags.get("qtc")),
    ]

    data = [header, values, flag_row]
    table = Table(data, colWidths=[doc_width() / 4] * 4)

    style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EFF6FF")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ("FONTNAME", (0, 0), (-1, 0), _FONT_BOLD),
        ("FONTNAME", (0, 1), (-1, 1), _FONT_BOLD),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTSIZE", (0, 2), (-1, 2), 8),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    # Color any abnormal flag cell red.
    for col, key in enumerate(("pr", "qrs", None, "qtc")):
        flag = flags.get(key) if key else None
        if flag and flag != "normal":
            style.append(("TEXTCOLOR", (col, 2), (col, 2), colors.HexColor("#B91C1C")))
            style.append(("TEXTCOLOR", (col, 1), (col, 1), colors.HexColor("#B91C1C")))
        elif flag == "normal":
            style.append(("TEXTCOLOR", (col, 2), (col, 2), colors.HexColor("#166534")))
    table.setStyle(TableStyle(style))

    return table


def _narrative_paragraphs(narrative: str) -> list[str]:
    """Split the LLM narrative into HTML-escaped paragraphs for reportlab.

    reportlab Paragraph parses a mini-HTML; raw &, <, > would break it, so escape
    them. Blank lines separate paragraphs.
    """
    escaped = narrative.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    blocks = [block.strip() for block in escaped.split("\n\n")]
    return [block.replace("\n", "<br/>") for block in blocks if block]


def _short_flag(flag: str | None) -> str:
    """Reduce an interval flag to a single status word for a narrow table cell.

    interpret_intervals returns rich strings like "prolonged (>200 ms) — consider
    first-degree AV block"; the first word ("prolonged"/"short"/"wide"/"normal")
    is enough for the at-a-glance table.
    """
    if not flag:
        return "—"
    return flag.split()[0]


def _diagnoses_table(report: ECGReport) -> Table:
    data = [["Diagnosis", "Probability", "Status"]]
    if not report.top_diagnoses:
        data.append(["No diagnoses returned", "—", "—"])
    for entry in report.top_diagnoses:
        status = "above threshold" if entry.above_threshold else "below threshold"
        data.append([entry.label, f"{entry.probability:.3f}", status])

    table = Table(data, colWidths=[doc_width() * f for f in (0.55, 0.22, 0.23)])
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), _FONT_BOLD),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for row, entry in enumerate(report.top_diagnoses, start=1):
        if entry.above_threshold:
            style.append(("FONTNAME", (0, row), (0, row), _FONT_BOLD))
    table.setStyle(TableStyle(style))
    return table


def _images_row(
    original_image: Image.Image | None,
    signal_image: Image.Image | None,
    styles: dict[str, ParagraphStyle],
) -> Table | None:
    """Lay the original photo (small) next to the digitized tracing (large)."""
    if original_image is None and signal_image is None:
        return None

    left_w = doc_width() * 0.34
    right_w = doc_width() * 0.62

    left_cell: list = []
    if original_image is not None:
        left_cell.append(_scaled_rl_image(original_image, max_width=left_w, max_height=70 * mm))
        left_cell.append(Paragraph("Original upload", styles["caption"]))
    right_cell: list = []
    if signal_image is not None:
        right_cell.append(_scaled_rl_image(signal_image, max_width=right_w, max_height=120 * mm))
        right_cell.append(Paragraph("Digitized 12-lead signal", styles["caption"]))

    table = Table([[left_cell, right_cell]], colWidths=[left_w + 6 * mm, right_w])
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return table


def _scaled_rl_image(
    image: Image.Image,
    *,
    max_width: float,
    max_height: float,
) -> RLImage:
    """Convert a PIL image to a reportlab Image scaled to fit a box (aspect kept)."""
    rgb = image.convert("RGB")
    buf = io.BytesIO()
    rgb.save(buf, format="PNG")
    buf.seek(0)

    width_px, height_px = rgb.size
    aspect = height_px / width_px if width_px else 1.0
    draw_w = max_width
    draw_h = draw_w * aspect
    if draw_h > max_height:
        draw_h = max_height
        draw_w = draw_h / aspect if aspect else max_width
    return RLImage(buf, width=draw_w, height=draw_h)


def _kv_table_style() -> TableStyle:
    return TableStyle(
        [
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#64748B")),
            ("TEXTCOLOR", (2, 0), (2, -1), colors.HexColor("#64748B")),
            ("FONTNAME", (1, 0), (1, -1), _FONT_BOLD),
            ("FONTNAME", (3, 0), (3, -1), _FONT_BOLD),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ]
    )


def doc_width() -> float:
    """Usable content width for A4 with the margins used by build_pdf_report."""
    return float(A4[0] - (18 * mm) * 2)
